<?xml version='1.0' encoding='UTF-8'?>
<definitions
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    xmlns:wsp="http://www.w3.org/ns/ws-policy"
    xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://soap_test.ats.uab.codes/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="http://soap_test.ats.uab.codes/"
    name="TestWebServiceService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://soap_test.ats.uab.codes/" schemaLocation="http://localhost:8080/soap-test/TestWebServiceService?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="sayHello">
        <part name="parameters" element="tns:sayHello"/>
    </message>
    <message name="sayHelloResponse">
        <part name="parameters" element="tns:sayHelloResponse"/>
    </message>
    <portType name="TestWebService">
        <operation name="sayHello">
            <input wsam:Action="http://soap_test.ats.uab.codes/TestWebService/sayHelloRequest" message="tns:sayHello"/>
            <output wsam:Action="http://soap_test.ats.uab.codes/TestWebService/sayHelloResponse" message="tns:sayHelloResponse"/>
        </operation>
    </portType>
    <binding name="TestWebServicePortBinding" type="tns:TestWebService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="sayHello">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="TestWebServiceService">
        <port name="TestWebServicePort" binding="tns:TestWebServicePortBinding">
            <soap:address location="http://localhost:8081/soap-test/TestWebServiceService"/>
        </port>
    </service>
</definitions>

